{% set name = "qcs-api-client-common" %}
{% set version = "0.11.2" %}

package:
  name: qcs-api-client-common-split
  version: {{ version }}

source:
  url: https://github.com/rigetti/qcs-api-client-rust/archive/refs/tags/common/v{{ version }}.tar.gz
  sha256: a66fedf0b4e6243c45b024e090b6aae527fea18b06a75b9742ea86b22b694b80

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin >=1.0.0,<2.0.0  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
  host:
    - maturin >=1.0.0,<2.0.0
    - python

outputs:
  - name: qcs_api_client_common
    requirements:
      host:
        - {{ pin_subpackage("qcs-api-client-common", exact=True) }}
      run:
        - {{ pin_subpackage("qcs-api-client-common", exact=True) }}
    test:
      imports:
        - qcs_api_client_common
      requires:
        - pip
      commands:
        - pip check

  - name: qcs-api-client-common
    script: install.sh  # [unix]
    script: install.bat  # [win]
    build:
      ignore_run_exports:
        - python
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python  # [build_platform != target_platform]
      host:
        - pip
        - python
        - setuptools
      run:
        - grpcio >=1.63.0
        - grpc-interceptor >=0.15.0
        - httpx >=0.27.0
        - python
    test:
      imports:
        - qcs_api_client_common
      requires:
        - pip
        - protobuf
        - pytest >=8.1.1
        - pytest-asyncio >=0.23.6
        - pytest-mock >=3.14.0
        - python
        - syrupy >=4.0.0
      source_files:
        - qcs-api-client-common/tests
        - qcs-api-client-common/tests_py
      commands:
        - pip check
        - cd qcs-api-client-common && pytest -v

about:
  home: https://github.com/rigetti/qcs-api-client-rust
  summary: 'Rust clients for Rigetti APIs'
  description: |
    Provides structures common to the gRPC and OpenAPI clients. In particular, it provides
    a ClientConfiguration type which is used to configure the clients using local QCS settings.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - MementoRC
  feedstock-name: qcs-api-client-common
